repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/motet-a/jinjalint
    rev: '01e0a4d8f1ee775aee00eb9d715eff2b4cc49e4d'  # select a tag / sha to point at
    hooks:
    -   id: jinjalint
